import type { ResourceConfig } from '@/types/crud'

import {
  accountStatusOptions,
  businessPlatformOptions,
  enabledStatusOptions,
  loginStatusOptions,
  runtimePlatformOptions,
  runtimeStatusOptions,
  scriptParamTypeOptions,
  slotStatusOptions,
  slotTypeOptions,
  taskStatusOptions,
  twoFaOptions,
} from './options'

const jsonPlaceholder = '{}'

export const resources: Record<string, ResourceConfig> = {
  accounts: {
    key: 'accounts',
    title: '账号管理',
    endpoint: '/api/accounts',
    createLabel: '新增账号',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'handle', label: 'Handle' },
      { key: 'login_username', label: '登录名' },
      { key: 'business_platform', label: '平台' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'login_status', label: '登录状态', type: 'status' },
      { key: 'bound_slot_id', label: 'Slot', type: 'id' },
      { key: 'proxy_id', label: '代理', type: 'id' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'status', label: '账号状态', type: 'select', options: accountStatusOptions },
      { key: 'login_status', label: '登录状态', type: 'select', options: loginStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: 'Handle / 昵称 / 登录名' },
    ],
    createFields: [
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'login_username', label: '登录用户名', required: true },
      { key: 'handle', label: 'Handle' },
      { key: 'display_name', label: '显示名称' },
      { key: 'platform_account_id', label: '平台账号 ID' },
      { key: 'avatar_url', label: '头像 URL' },
      { key: 'profile_url', label: '主页 URL' },
      { key: 'password_secret_ref', label: '密码密文引用' },
      { key: 'twofa_type', label: '2FA 类型', type: 'select', options: twoFaOptions, defaultValue: 'none' },
      { key: 'totp_secret_ref', label: 'TOTP 引用' },
      { key: 'backup_code_ref', label: '备用码引用' },
      { key: 'status', label: '状态', type: 'select', options: accountStatusOptions, defaultValue: 'normal' },
      { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2, placeholder: jsonPlaceholder },
    ],
    updateFields: [
      { key: 'login_username', label: '登录用户名' },
      { key: 'handle', label: 'Handle' },
      { key: 'display_name', label: '显示名称' },
      { key: 'platform_account_id', label: '平台账号 ID' },
      { key: 'avatar_url', label: '头像 URL' },
      { key: 'profile_url', label: '主页 URL' },
      { key: 'password_secret_ref', label: '密码密文引用' },
      { key: 'twofa_type', label: '2FA 类型', type: 'select', options: twoFaOptions },
      { key: 'totp_secret_ref', label: 'TOTP 引用' },
      { key: 'backup_code_ref', label: '备用码引用' },
      { key: 'status', label: '状态', type: 'select', options: accountStatusOptions },
      { key: 'metadata', label: '扩展数据', type: 'json', span: 2 },
    ],
    rowActions: [
      {
        key: 'bind-slot',
        label: '绑定 Slot',
        method: 'POST',
        icon: 'link',
        path: (record) => `/api/accounts/${record.id}/bind-slot`,
        fields: [
          { key: 'slot_id', label: 'Slot ID', required: true },
          { key: 'remark', label: '备注' },
        ],
      },
      {
        key: 'bind-proxy',
        label: '绑定代理',
        method: 'POST',
        icon: 'link',
        path: (record) => `/api/accounts/${record.id}/bind-proxy`,
        fields: [
          { key: 'proxy_id', label: '代理 ID', required: true },
          { key: 'remark', label: '备注' },
        ],
      },
      {
        key: 'unbind-proxy',
        label: '解绑代理',
        method: 'POST',
        icon: 'unlink',
        path: (record) => `/api/accounts/${record.id}/unbind-proxy`,
        confirm: '确认解绑该账号代理？',
      },
      {
        key: 'login-task',
        label: '创建登录任务',
        method: 'POST',
        icon: 'play',
        path: (record) => `/api/accounts/${record.id}/login-task`,
        fields: [
          { key: 'slot_id', label: 'Slot ID' },
          { key: 'credential_ref', label: '凭据引用' },
          { key: 'twofa_mode', label: '2FA 模式', type: 'select', options: twoFaOptions },
          { key: 'login_check_after_success', label: '登录后检测', type: 'boolean', defaultValue: true },
          { key: 'params', label: '任务参数', type: 'json', defaultValue: {}, span: 2 },
        ],
      },
      {
        key: 'login-check-task',
        label: '登录检测任务',
        method: 'POST',
        icon: 'play',
        path: (record) => `/api/accounts/${record.id}/login-check-task`,
        fields: [
          { key: 'slot_id', label: 'Slot ID' },
          { key: 'params', label: '任务参数', type: 'json', defaultValue: {}, span: 2 },
        ],
      },
      { key: 'metrics', label: '指标快照', method: 'GET', icon: 'list', path: (record) => `/api/accounts/${record.id}/metrics`, refresh: false },
    ],
    archiveLabel: '',
  },

  accountGroups: {
    key: 'accountGroups',
    title: '账号分组',
    endpoint: '/api/account-groups',
    createLabel: '新增账号组',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'name', label: '名称' },
      { key: 'business_platform', label: '平台' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'member_count', label: '成员数' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: '名称 / 描述' },
    ],
    createFields: [
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'name', label: '名称', required: true },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions, defaultValue: 'enabled' },
      { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 },
    ],
    updateFields: [
      { key: 'name', label: '名称' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
      { key: 'metadata', label: '扩展数据', type: 'json', span: 2 },
    ],
    rowActions: [
      {
        key: 'add-account',
        label: '添加账号',
        method: 'POST',
        icon: 'users',
        path: (record) => `/api/account-groups/${record.id}/accounts`,
        fields: [
          { key: 'account_id', label: '账号 ID', required: true },
          { key: 'sort_order', label: '排序', type: 'number' },
          { key: 'remark', label: '备注' },
          { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 },
        ],
      },
      { key: 'list-accounts', label: '查看成员', method: 'GET', icon: 'list', path: (record) => `/api/account-groups/${record.id}/accounts`, params: { page: 1, page_size: 100 }, refresh: false },
      {
        key: 'remove-account',
        label: '移除账号',
        method: 'DELETE',
        icon: 'trash',
        variant: 'danger',
        path: (record, payload) => `/api/account-groups/${record.id}/accounts/${payload?.account_id}`,
        fields: [{ key: 'account_id', label: '账号 ID', required: true }],
        confirm: '确认从账号组移除该账号？',
      },
    ],
    archiveLabel: '归档',
  },

  slots: {
    key: 'slots',
    title: 'Execution Slot',
    endpoint: '/api/execution-slots',
    createLabel: '新增 Slot',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'display_name', label: '名称' },
      { key: 'provider_slot_id', label: 'Provider ID' },
      { key: 'runtime_platform', label: '执行平台' },
      { key: 'provider', label: '供应商' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'bound_account_id', label: '账号', type: 'id' },
      { key: 'proxy_id', label: '代理', type: 'id' },
      { key: 'last_seen_at', label: '心跳', type: 'datetime' },
    ],
    filters: [
      { key: 'provider', label: '供应商', placeholder: 'adspower' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'status', label: '状态', type: 'select', options: slotStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: 'Profile ID / 编号 / 名称' },
    ],
    createFields: [
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions, defaultValue: 'fingerprint_browser' },
      { key: 'provider', label: '供应商', defaultValue: 'adspower' },
      { key: 'slot_type', label: 'Slot 类型', type: 'select', options: slotTypeOptions, defaultValue: 'fingerprint_profile' },
      { key: 'provider_slot_id', label: 'Provider Slot ID', required: true },
      { key: 'provider_slot_no', label: 'Provider 编号' },
      { key: 'slot_key', label: 'Slot Key' },
      { key: 'display_name', label: '显示名称' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 },
    ],
    updateFields: [
      { key: 'provider_slot_no', label: 'Provider 编号' },
      { key: 'slot_key', label: 'Slot Key' },
      { key: 'display_name', label: '显示名称' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'status', label: '状态', type: 'select', options: slotStatusOptions },
      { key: 'metadata', label: '扩展数据', type: 'json', span: 2 },
    ],
    rowActions: [
      { key: 'bind-account', label: '绑定账号', method: 'POST', icon: 'link', path: (record) => `/api/execution-slots/${record.id}/bind-account`, fields: [{ key: 'account_id', label: '账号 ID', required: true }, { key: 'remark', label: '备注' }] },
      { key: 'bind-proxy', label: '绑定代理', method: 'POST', icon: 'link', path: (record) => `/api/execution-slots/${record.id}/bind-proxy`, fields: [{ key: 'proxy_id', label: '代理 ID', required: true }, { key: 'remark', label: '备注' }] },
      { key: 'unbind-proxy', label: '解绑代理', method: 'POST', icon: 'unlink', path: (record) => `/api/execution-slots/${record.id}/unbind-proxy`, confirm: '确认解绑该 Slot 代理？' },
      { key: 'enable', label: '启用', method: 'POST', icon: 'power', path: (record) => `/api/execution-slots/${record.id}/enable`, variant: 'success' },
      { key: 'disable', label: '禁用', method: 'POST', icon: 'powerOff', path: (record) => `/api/execution-slots/${record.id}/disable`, variant: 'danger', confirm: '确认禁用该 Slot？' },
      { key: 'runtime', label: '关联 Runtime', method: 'GET', icon: 'list', path: (record) => `/api/execution-slots/${record.id}/runtime`, refresh: false },
    ],
    archiveLabel: '',
  },

  slotGroups: {
    key: 'slotGroups',
    title: 'Slot 分组',
    endpoint: '/api/slot-groups',
    createLabel: '新增 Slot 组',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'name', label: '名称' },
      { key: 'runtime_platform', label: '执行平台' },
      { key: 'provider', label: '供应商' },
      { key: 'business_platform', label: '平台' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'member_count', label: '成员数' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions },
      { key: 'provider', label: '供应商', placeholder: 'adspower' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: '名称 / 描述' },
    ],
    createFields: [
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions, defaultValue: 'fingerprint_browser' },
      { key: 'provider', label: '供应商', defaultValue: 'adspower' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'name', label: '名称', required: true },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions, defaultValue: 'enabled' },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
      { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 },
    ],
    updateFields: [
      { key: 'name', label: '名称' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
      { key: 'metadata', label: '扩展数据', type: 'json', span: 2 },
    ],
    rowActions: [
      { key: 'add-slot', label: '添加 Slot', method: 'POST', icon: 'link', path: (record) => `/api/slot-groups/${record.id}/slots`, fields: [{ key: 'slot_id', label: 'Slot ID', required: true }, { key: 'sort_order', label: '排序', type: 'number' }, { key: 'remark', label: '备注' }, { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 }] },
      { key: 'list-slots', label: '查看成员', method: 'GET', icon: 'list', path: (record) => `/api/slot-groups/${record.id}/slots`, params: { page: 1, page_size: 100 }, refresh: false },
      { key: 'remove-slot', label: '移除 Slot', method: 'DELETE', icon: 'trash', variant: 'danger', path: (record, payload) => `/api/slot-groups/${record.id}/slots/${payload?.slot_id}`, fields: [{ key: 'slot_id', label: 'Slot ID', required: true }], confirm: '确认从 Slot 组移除该 Slot？' },
    ],
    archiveLabel: '归档',
  },

  proxies: {
    key: 'proxies',
    title: '代理资源',
    endpoint: '/api/resource-center/proxies',
    createEndpoint: '/api/resource-center/proxies/import',
    createLabel: '导入代理',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'name', label: '名称' },
      { key: 'proxy_type', label: '类型' },
      { key: 'host', label: 'Host' },
      { key: 'port', label: '端口' },
      { key: 'username', label: '用户' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: '名称 / Host / 用户名 / 备注' },
    ],
    createFields: [
      { key: 'name', label: '代理名称', required: true },
      { key: 'proxy_url', label: 'Socks5 地址', required: true, placeholder: 'socks5://user:pass@127.0.0.1:1080' },
      { key: 'remark', label: '备注', span: 2 },
      { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 },
    ],
    updateFields: [
      { key: 'name', label: '代理名称' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'remark', label: '备注', span: 2 },
      { key: 'metadata', label: '扩展数据', type: 'json', span: 2 },
    ],
    rowActions: [
      { key: 'bindings', label: '绑定关系', method: 'GET', icon: 'list', path: (record) => `/api/resource-center/proxies/${record.id}/bindings`, refresh: false },
      { key: 'enable', label: '启用', method: 'POST', icon: 'power', path: (record) => `/api/resource-center/proxies/${record.id}/enable`, variant: 'success' },
      { key: 'disable', label: '禁用', method: 'POST', icon: 'powerOff', path: (record) => `/api/resource-center/proxies/${record.id}/disable`, variant: 'danger', confirm: '确认禁用该代理？' },
    ],
    archiveLabel: '归档',
  },

  scripts: {
    key: 'scripts',
    title: '脚本管理',
    endpoint: '/api/scripts',
    createLabel: '新增脚本',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'name', label: '名称' },
      { key: 'engine_type', label: '引擎' },
      { key: 'supported_business_platforms', label: '平台', type: 'list' },
      { key: 'max_concurrency', label: '并发' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'engine_type', label: '执行引擎', placeholder: 'browser_runtime' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions },
      { key: 'provider', label: '供应商', placeholder: 'adspower' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'keyword', label: '关键词', placeholder: 'Key / 名称 / 描述' },
    ],
    createFields: [
      { key: 'script_key', label: '脚本 Key', required: true },
      { key: 'name', label: '脚本名称', required: true },
      { key: 'engine_type', label: '执行引擎', defaultValue: 'browser_runtime' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions, defaultValue: 'enabled' },
      { key: 'supported_runtime_platforms', label: '执行平台范围', type: 'tags', defaultValue: ['fingerprint_browser'] },
      { key: 'supported_providers', label: '供应商范围', type: 'tags', defaultValue: ['adspower'] },
      { key: 'supported_business_platforms', label: '业务平台范围', type: 'tags', defaultValue: ['threads'] },
      { key: 'default_timeout_seconds', label: '默认超时秒', type: 'number', defaultValue: 3600 },
      { key: 'max_timeout_seconds', label: '最大超时秒', type: 'number', defaultValue: 3600 },
      { key: 'max_concurrency', label: '最大并发', type: 'number', defaultValue: 1 },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
    ],
    updateFields: [
      { key: 'name', label: '脚本名称' },
      { key: 'engine_type', label: '执行引擎' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'supported_runtime_platforms', label: '执行平台范围', type: 'tags' },
      { key: 'supported_providers', label: '供应商范围', type: 'tags' },
      { key: 'supported_business_platforms', label: '业务平台范围', type: 'tags' },
      { key: 'default_timeout_seconds', label: '默认超时秒', type: 'number' },
      { key: 'max_timeout_seconds', label: '最大超时秒', type: 'number' },
      { key: 'max_concurrency', label: '最大并发', type: 'number' },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
    ],
    rowActions: [
      { key: 'detail', label: '详情与参数', method: 'GET', icon: 'list', path: (record) => `/api/scripts/${record.id}/detail`, refresh: false },
      { key: 'params', label: '参数列表', method: 'GET', icon: 'list', path: (record) => `/api/scripts/${record.id}/params`, refresh: false },
      { key: 'add-param', label: '新增参数', method: 'POST', icon: 'copy', path: (record) => `/api/scripts/${record.id}/params`, fields: [{ key: 'param_key', label: '参数 Key', required: true }, { key: 'name', label: '参数名称', required: true }, { key: 'param_type', label: '参数类型', type: 'select', options: scriptParamTypeOptions, required: true }, { key: 'required', label: '必填', type: 'boolean' }, { key: 'sort_order', label: '排序', type: 'number', defaultValue: 0 }, { key: 'description', label: '描述', type: 'textarea', span: 2 }, { key: 'default_value', label: '默认值', type: 'json', defaultValue: null, span: 2 }, { key: 'options', label: '枚举选项', type: 'json', defaultValue: [], span: 2 }, { key: 'validation', label: '校验规则', type: 'json', defaultValue: {}, span: 2 }, { key: 'resource_selector', label: '资源选择器', type: 'json', defaultValue: {}, span: 2 }, { key: 'metadata', label: '扩展数据', type: 'json', defaultValue: {}, span: 2 }] },
      { key: 'enable', label: '启用', method: 'POST', icon: 'power', path: (record) => `/api/scripts/${record.id}/enable`, variant: 'success' },
      { key: 'disable', label: '禁用', method: 'POST', icon: 'powerOff', path: (record) => `/api/scripts/${record.id}/disable`, variant: 'danger', confirm: '确认禁用该脚本？' },
    ],
    archiveLabel: '归档',
  },

  taskTemplates: {
    key: 'taskTemplates',
    title: '任务模板',
    endpoint: '/api/task-templates',
    createLabel: '新增模板',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'template_key', label: '模板 Key' },
      { key: 'name', label: '名称' },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'business_platform', label: '平台' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'updated_at', label: '更新时间', type: 'datetime' },
    ],
    filters: [
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'keyword', label: '关键词', placeholder: 'Key / 名称 / 描述' },
    ],
    createFields: [
      { key: 'template_key', label: '模板 Key', required: true },
      { key: 'name', label: '模板名称', required: true },
      { key: 'script_key', label: '脚本 Key', required: true },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'engine_type', label: '执行引擎', defaultValue: 'browser_runtime' },
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions, defaultValue: 'fingerprint_browser' },
      { key: 'provider', label: '供应商', defaultValue: 'adspower' },
      { key: 'default_timeout_seconds', label: '默认超时秒', type: 'number', defaultValue: 3600 },
      { key: 'account_scope_type', label: '账号范围', defaultValue: 'single_account' },
      { key: 'execution_mode', label: '执行模式', defaultValue: 'immediate' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions, defaultValue: 'enabled' },
      { key: 'slot_id', label: '默认 Slot ID' },
      { key: 'slot_group_id', label: '默认 Slot 组 ID' },
      { key: 'account_ids', label: '账号 ID 列表', type: 'tags', defaultValue: [], span: 2 },
      { key: 'account_group_ids', label: '账号组 ID 列表', type: 'tags', defaultValue: [], span: 2 },
      { key: 'default_params', label: '默认参数', type: 'json', defaultValue: {}, span: 2 },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
    ],
    updateFields: [
      { key: 'name', label: '模板名称' },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'engine_type', label: '执行引擎' },
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions },
      { key: 'provider', label: '供应商' },
      { key: 'default_timeout_seconds', label: '默认超时秒', type: 'number' },
      { key: 'account_scope_type', label: '账号范围' },
      { key: 'execution_mode', label: '执行模式' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
      { key: 'slot_id', label: '默认 Slot ID' },
      { key: 'slot_group_id', label: '默认 Slot 组 ID' },
      { key: 'account_ids', label: '账号 ID 列表', type: 'tags', span: 2 },
      { key: 'account_group_ids', label: '账号组 ID 列表', type: 'tags', span: 2 },
      { key: 'default_params', label: '默认参数', type: 'json', span: 2 },
      { key: 'description', label: '描述', type: 'textarea', span: 2 },
    ],
    rowActions: [
      { key: 'clone', label: '克隆模板', method: 'POST', icon: 'copy', path: (record) => `/api/task-templates/${record.id}/clone`, fields: [{ key: 'template_key', label: '新模板 Key', required: true }, { key: 'name', label: '新模板名称' }] },
      { key: 'create-task', label: '创建任务', method: 'POST', icon: 'play', path: (record) => `/api/task-templates/${record.id}/create-task`, fields: [{ key: 'title', label: '任务标题' }, { key: 'account_id', label: '账号 ID' }, { key: 'slot_id', label: 'Slot ID' }, { key: 'timeout_seconds', label: '超时秒', type: 'number' }, { key: 'scheduled_at', label: '计划时间', type: 'datetime' }, { key: 'params', label: '覆盖参数', type: 'json', defaultValue: {}, span: 2 }] },
      { key: 'create-tasks', label: '批量创建', method: 'POST', icon: 'play', path: (record) => `/api/task-templates/${record.id}/create-tasks`, fields: [{ key: 'title_prefix', label: '标题前缀' }, { key: 'account_ids', label: '账号 ID 列表', type: 'tags', defaultValue: [], span: 2 }, { key: 'account_group_ids', label: '账号组 ID 列表', type: 'tags', defaultValue: [], span: 2 }, { key: 'slot_ids', label: 'Slot ID 列表', type: 'tags', defaultValue: [], span: 2 }, { key: 'slot_group_id', label: 'Slot 组 ID' }, { key: 'timeout_seconds', label: '超时秒', type: 'number' }, { key: 'scheduled_at', label: '计划时间', type: 'datetime' }, { key: 'params', label: '覆盖参数', type: 'json', defaultValue: {}, span: 2 }] },
    ],
    archiveLabel: '归档',
  },

  tasks: {
    key: 'tasks',
    title: '任务管理',
    endpoint: '/api/tasks',
    createLabel: '新增任务',
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'title', label: '标题' },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'business_platform', label: '平台' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'account_id', label: '账号', type: 'id' },
      { key: 'slot_id', label: 'Slot', type: 'id' },
      { key: 'created_at', label: '创建时间', type: 'datetime' },
    ],
    filters: [
      { key: 'status', label: '状态', type: 'select', options: taskStatusOptions },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions },
      { key: 'script_key', label: '脚本 Key' },
      { key: 'account_id', label: '账号 ID' },
    ],
    createFields: [
      { key: 'title', label: '任务标题' },
      { key: 'task_type', label: '任务类型', defaultValue: 'manual' },
      { key: 'script_key', label: '脚本 Key', required: true },
      { key: 'business_platform', label: '业务平台', type: 'select', options: businessPlatformOptions, defaultValue: 'threads' },
      { key: 'engine_type', label: '执行引擎', defaultValue: 'browser_runtime' },
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions, defaultValue: 'fingerprint_browser' },
      { key: 'provider', label: '供应商', defaultValue: 'adspower' },
      { key: 'account_id', label: '账号 ID' },
      { key: 'slot_id', label: 'Slot ID' },
      { key: 'timeout_seconds', label: '超时秒', type: 'number', defaultValue: 3600 },
      { key: 'scheduled_at', label: '计划时间', type: 'datetime' },
      { key: 'params', label: '任务参数', type: 'json', defaultValue: {}, span: 2 },
    ],
    updateFields: [],
    rowActions: [
      { key: 'cancel', label: '取消任务', method: 'POST', icon: 'powerOff', variant: 'danger', path: (record) => `/api/tasks/${record.id}/cancel`, confirm: '确认取消该任务？' },
      { key: 'assignments', label: '分配记录', method: 'GET', icon: 'list', path: (record) => `/api/tasks/${record.id}/assignments`, refresh: false },
      { key: 'events', label: '事件日志', method: 'GET', icon: 'list', path: (record) => `/api/tasks/${record.id}/events`, refresh: false },
    ],
    archiveLabel: '',
  },

  runtimes: {
    key: 'runtimes',
    title: 'Runtime 在线状态',
    endpoint: '/api/runtimes',
    readOnly: true,
    columns: [
      { key: 'id', label: 'ID', type: 'id' },
      { key: 'runtime_id', label: 'Runtime ID' },
      { key: 'runtime_platform', label: '执行平台' },
      { key: 'provider', label: '供应商' },
      { key: 'status', label: '状态', type: 'status' },
      { key: 'slot_total', label: 'Slot 总数' },
      { key: 'slot_idle', label: '空闲' },
      { key: 'slot_running', label: '运行中' },
      { key: 'last_heartbeat_at', label: '心跳', type: 'datetime' },
    ],
    filters: [
      { key: 'status', label: '状态', type: 'select', options: runtimeStatusOptions },
      { key: 'provider', label: '供应商', placeholder: 'adspower' },
      { key: 'runtime_platform', label: '执行平台', type: 'select', options: runtimePlatformOptions },
    ],
    rowActions: [
      { key: 'slots', label: '查看 Slot', method: 'GET', icon: 'list', path: (record) => `/api/runtimes/${record.id}/slots`, refresh: false },
    ],
    archiveLabel: '',
  },
}
